def GIT_REPO_URL = "git@github.com:andersjio/nx-examples.git"
def BRANCH_NAME = "main"
def WORK_TIME_SIMULATION = 10
def testPodYaml = """
spec:
  containers:
  - name: test-pod
    image: nx-example-build-node:14.17.4
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    args:
    - infinity
    resources:
      limits:
        memory: "1000Mi"
      requests:
        memory: "500Mi"
    livenessProbe:
      exec:
        command:
          - bin/bash
          - -c
          - ./liveness.sh
      initialDelaySeconds: 60
      timeoutSeconds: 25
"""

kubectlYaml= """
spec:
  containers:
  - name: alpine-pod
    image: alpine/git
    command:
    - sleep
    args:
    - infinity
"""

pipeline {
    options{
        timestamps()
        skipDefaultCheckout()
    }
    agent {
        kubernetes {
            label "${JOB_NAME}-${BUILD_NUMBER}-pipeline"
            yaml kubectlYaml
            showRawYaml false
            workspaceVolume dynamicPVC(accessModes: "ReadWriteMany", requestsSize: "2Gi", storageClassName: "standard")
        }
    }
    stages {
        stage('Checkout source code'){
            steps {
                container('test-pod') {
                  git branch: "$BRANCH_NAME",
                  credentialsId: 'private-ssh',
                  url: "$GIT_REPO_URL"
                }
            }
        }
        stage("Set env"){
            steps{
                container('alpine-pod'){
                    script {
                        env.WORKSPACE_PVC = "pvc-workspace-${JENKINS_AGENT_NAME}"
                    }
                }
            }
        }
        stage('Yarn') {
            agent {
                kubernetes {
                    label "${JOB_NAME}-${BUILD_NUMBER}-yarn"
                    yaml testPodYaml
                    workspaceVolume persistentVolumeClaimWorkspaceVolume(claimName: "$WORKSPACE_PVC", readOnly: false)
					          showRawYaml false
                }
            }
            stages{
                stage('Yarn install'){
                    steps{
                        container('test-pod'){
                            sh """yarn install --parallel --maxParallel=4 """
                        }
                    }
                }
                stage('Linting'){
                    steps{
                        container('test-pod'){
							            sh " nx run-many --target=lint --all --parallel --maxParallel=4"
                        }
                    }
                }
            }
        }
        stage('Lint') {
            agent {
                kubernetes {
                    label "${JOB_NAME}-${BUILD_NUMBER}-lint"
                    yaml testPodYaml
                    workspaceVolume persistentVolumeClaimWorkspaceVolume(claimName: "$WORKSPACE_PVC", readOnly: false)
					          showRawYaml false
                }
            }
            stages{
                stage('Linting'){
                    steps{
                        container('test-pod'){
							            sh " nx run-many --target=lint --all --parallel --maxParallel=4"
                        }
                    }
                }
            }
        }
        stage('Stages to run in Parallel') {
            steps {
                script {
                    def json = readJSON file: 'projects.json'
                    def nx_projects = json["projects"]
                    parallel nx_projects.collectEntries {
                        ["${it}" : generateUnitTestStage(it, testPodYaml, "$WORKSPACE_PVC", "$WORK_TIME_SIMULATION")]
                    }
                }
            }
        }
    }
    post {
        always {
            container('alpine-pod'){
				      junit (allowEmptyResults: true, testResults: "**/test-results-unit.xml")
            }
        }
    }
}

def generateUnitTestStage(job, pod_file, pvc, work_time_simulation) {
    return {
        def project = job
        stage(job) {
            podTemplate(
                yaml:pod_file,
                showRawYaml: false,
                workspaceVolume: persistentVolumeClaimWorkspaceVolume(claimName: pvc, readOnly: false)
                )  {
                node(POD_LABEL) {
                    stage("Unit test ${job}") {
                        container('test-pod') {
                            sh """
                                echo "Running tests for project: ${job} in $HOSTNAME"
                                nx run-many --target=test --projects ${job}  --coverage
                                sleep ${work_time_simulation} #Strictly added to simulate a bit of build time per pod
                                echo "Done with tests for ${job}"
                            """
                        }
                    }
                }
            }
        }
    }
}
